// export type Action =
//   { type: "PUSH_NEW_ROUTE", route: string }
//   | { type: "POP_ROUTE" }
//   | { type: "POP_TO_ROUTE", route: string }
//   | { type: "REPLACE_ROUTE", route: string }
//   | { type: "REPLACE_OR_PUSH_ROUTE", route: string }
//   | { type: "OPEN_DRAWER" }
//   | { type: "CLOSE_DRAWER" }
//   | { type: "SET_USER", name: string }
//   | { type: "SET_LIST", list: string }

// export type Dispatch = (action: Action | Array<Action>) => any;
// export type GetState = () => Object;
// export type PromiseAction = Promise<Action>;

export const SETTING_ENV = "SETTING_ENV";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";

export const USER_SCAN_REQUESTED = "USER_SCAN_REQUESTED";
export const USER_SCAN_SUCCESS = "USER_SCAN_SUCCESS";
export const USER_SCAN_FAILED = "USER_SCAN_FAILED";

export const SCAN_HISTORY_REQUESTED = "SCAN_HISTORY_REQUESTED";
export const SCAN_HISTORY_SUCCESS = "SCAN_HISTORY_SUCCESS";
export const SCAN_HISTORY_FAILED = "SCAN_HISTORY_FAILED";

export const SWITCH_ENVIRONMENT = "SWITCH_ENVIRONMENT";
export const SWITCH_BUNDLE = "SWITCH_BUNDLE";

export const IMAGE_CAPTURE = "IMAGE_CAPTURE";

export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const FETCH_DATA_SUCESS = "FETCH_DATA_SUCESS";

export const FETCH_BOOKING_DATA_1 = "FETCH_BOOKING_DATA_1";
export const FETCH_BOOKING_DATA_FAILED_1 = "FETCH_BOOKING_DATA_FAILED_1";
export const FETCH_BOOKING_DATA_SUCESS_1 = "FETCH_BOOKING_DATA_SUCESS_1";

export const FETCH_BOOKING_DATA_2 = "FETCH_BOOKING_DATA_2";
export const FETCH_BOOKING_DATA_FAILED_2 = "FETCH_BOOKING_DATA_FAILED_2";
export const FETCH_BOOKING_DATA_SUCESS_2 = "FETCH_BOOKING_DATA_SUCESS_2";

export const FETCH_BOOKING_DATA_3 = "FETCH_BOOKING_DATA_3";
export const FETCH_BOOKING_DATA_FAILED_3 = "FETCH_BOOKING_DATA_FAILED_3";
export const FETCH_BOOKING_DATA_SUCESS_3 = "FETCH_BOOKING_DATA_SUCESS_3";

export const FETCH_BOOKING_DATA_4 = "FETCH_BOOKING_DATA_4";
export const FETCH_BOOKING_DATA_FAILED_4 = "FETCH_BOOKING_DATA_FAILED_4";
export const FETCH_BOOKING_DATA_SUCESS_4 = "FETCH_BOOKING_DATA_SUCESS_4";

export const FETCH_BOOKING_DATA_5 = "FETCH_BOOKING_DATA_5";
export const FETCH_BOOKING_DATA_FAILED_5 = "FETCH_BOOKING_DATA_FAILED_5";
export const FETCH_BOOKING_DATA_SUCESS_5 = "FETCH_BOOKING_DATA_SUCESS_5";

export const FETCH_BOOKING_DATA_6 = "FETCH_BOOKING_DATA_6";
export const FETCH_BOOKING_DATA_FAILED_6 = "FETCH_BOOKING_DATA_FAILED_6";
export const FETCH_BOOKING_DATA_SUCESS_6 = "FETCH_BOOKING_DATA_SUCESS_6";


export const FETCH_PROFILE_DATA = "FETCH_PROFILE_DATA";
export const FETCH_PROFILE_DATA_FAILED = "FETCH_PROFILE_DATA_FAILED";
export const FETCH_PROFILE_DATA_SUCESS = "FETCH_PROFILE_DATA_SUCESS";

export const GOOGLE_MAP_AUTOCOMPLETE_LOC1 = "GOOGLE_MAP_AUTOCOMPLETE_LOC1";
export const GOOGLE_MAP_AUTOCOMPLETE_LOC2 = "GOOGLE_MAP_AUTOCOMPLETE_LOC2";
export const CORP_GOOGLE_MAP_AUTOCOMPLETE_LOC = "CORP_GOOGLE_MAP_AUTOCOMPLETE_LOC";
export const RESET_GOOGLE_MAP_AUTOCOMPLETE_LOC1AND2 = "RESET_GOOGLE_MAP_AUTOCOMPLETE_LOC1AND2";

export const START_NEW_BOOKING = "START_NEW_BOOKING";
export const NEW_BOOKING_FAILED = "NEW_BOOKING_FAILED";
export const NEW_BOOKING_SUCESS = "NEW_BOOKING_SUCESS";

export const FETCH_CORPORATE_BOOKING_DATA_1 = "FETCH_CORPORATE_BOOKING_DATA_1";
export const FETCH_CORPORATE_BOOKING_DATA_FAILED_1 = "FETCH_CORPORATE_BOOKING_DATA_FAILED_1";
export const FETCH_CORPORATE_BOOKING_DATA_SUCESS_1 = "FETCH_CORPORATE_BOOKING_DATA_SUCESS_1";

export const FETCH_GPS_DEVICE_FAILED = "FETCH_GPS_DEVICE_FAILED";
export const GET_PAYMENT_AMT_FOR_TRIP = "GET_PAYMENT_AMT_FOR_TRIP";

